// Code generated by protoc-gen-go. DO NOT EDIT.
// source: calculator/calculatorpb/calculator.proto

package calculatorpb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Calculation struct {
	A                    int32    `protobuf:"varint,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    int32    `protobuf:"varint,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Calculation) Reset()         { *m = Calculation{} }
func (m *Calculation) String() string { return proto.CompactTextString(m) }
func (*Calculation) ProtoMessage()    {}
func (*Calculation) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{0}
}

func (m *Calculation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Calculation.Unmarshal(m, b)
}
func (m *Calculation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Calculation.Marshal(b, m, deterministic)
}
func (m *Calculation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Calculation.Merge(m, src)
}
func (m *Calculation) XXX_Size() int {
	return xxx_messageInfo_Calculation.Size(m)
}
func (m *Calculation) XXX_DiscardUnknown() {
	xxx_messageInfo_Calculation.DiscardUnknown(m)
}

var xxx_messageInfo_Calculation proto.InternalMessageInfo

func (m *Calculation) GetA() int32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *Calculation) GetB() int32 {
	if m != nil {
		return m.B
	}
	return 0
}

type CalculationRequest struct {
	Calculation          *Calculation `protobuf:"bytes,1,opt,name=calculation,proto3" json:"calculation,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *CalculationRequest) Reset()         { *m = CalculationRequest{} }
func (m *CalculationRequest) String() string { return proto.CompactTextString(m) }
func (*CalculationRequest) ProtoMessage()    {}
func (*CalculationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{1}
}

func (m *CalculationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationRequest.Unmarshal(m, b)
}
func (m *CalculationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationRequest.Marshal(b, m, deterministic)
}
func (m *CalculationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationRequest.Merge(m, src)
}
func (m *CalculationRequest) XXX_Size() int {
	return xxx_messageInfo_CalculationRequest.Size(m)
}
func (m *CalculationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationRequest proto.InternalMessageInfo

func (m *CalculationRequest) GetCalculation() *Calculation {
	if m != nil {
		return m.Calculation
	}
	return nil
}

type CalculationResponse struct {
	Result               int32    `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CalculationResponse) Reset()         { *m = CalculationResponse{} }
func (m *CalculationResponse) String() string { return proto.CompactTextString(m) }
func (*CalculationResponse) ProtoMessage()    {}
func (*CalculationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_7f42938f8c8365cf, []int{2}
}

func (m *CalculationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CalculationResponse.Unmarshal(m, b)
}
func (m *CalculationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CalculationResponse.Marshal(b, m, deterministic)
}
func (m *CalculationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CalculationResponse.Merge(m, src)
}
func (m *CalculationResponse) XXX_Size() int {
	return xxx_messageInfo_CalculationResponse.Size(m)
}
func (m *CalculationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CalculationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CalculationResponse proto.InternalMessageInfo

func (m *CalculationResponse) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

func init() {
	proto.RegisterType((*Calculation)(nil), "calculator.Calculation")
	proto.RegisterType((*CalculationRequest)(nil), "calculator.CalculationRequest")
	proto.RegisterType((*CalculationResponse)(nil), "calculator.CalculationResponse")
}

func init() {
	proto.RegisterFile("calculator/calculatorpb/calculator.proto", fileDescriptor_7f42938f8c8365cf)
}

var fileDescriptor_7f42938f8c8365cf = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x48, 0x4e, 0xcc, 0x49,
	0x2e, 0xcd, 0x49, 0x2c, 0xc9, 0x2f, 0xd2, 0x47, 0x30, 0x0b, 0x92, 0x90, 0x38, 0x7a, 0x05, 0x45,
	0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x08, 0x11, 0x25, 0x4d, 0x2e, 0x6e, 0x67, 0x28, 0x2f, 0x33, 0x3f,
	0x4f, 0x88, 0x87, 0x8b, 0x31, 0x51, 0x82, 0x51, 0x81, 0x51, 0x83, 0x35, 0x88, 0x31, 0x11, 0xc4,
	0x4b, 0x92, 0x60, 0x82, 0xf0, 0x92, 0x94, 0xfc, 0xb9, 0x84, 0x90, 0x94, 0x06, 0xa5, 0x16, 0x96,
	0xa6, 0x16, 0x97, 0x08, 0x59, 0x72, 0x71, 0x27, 0x23, 0x44, 0xc1, 0x7a, 0xb9, 0x8d, 0xc4, 0xf5,
	0x90, 0x2c, 0x45, 0xd6, 0x84, 0xac, 0x56, 0x49, 0x97, 0x4b, 0x18, 0xc5, 0xc0, 0xe2, 0x82, 0xfc,
	0xbc, 0xe2, 0x54, 0x21, 0x31, 0x2e, 0xb6, 0xa2, 0xd4, 0xe2, 0xd2, 0x9c, 0x12, 0xa8, 0x43, 0xa0,
	0x3c, 0xa3, 0x34, 0x14, 0xfb, 0x83, 0x53, 0x8b, 0xca, 0x32, 0x93, 0x53, 0x85, 0x02, 0x50, 0x3d,
	0x20, 0x87, 0xcb, 0x66, 0x88, 0x73, 0xa5, 0xe4, 0x71, 0xca, 0x43, 0x6c, 0x57, 0x62, 0x70, 0xe2,
	0x8b, 0xe2, 0x41, 0x0e, 0xbf, 0x24, 0x36, 0x70, 0xa8, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0xc2, 0x14, 0xfc, 0x8c, 0x61, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// CalculationServiceClient is the client API for CalculationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CalculationServiceClient interface {
	// Unary call
	Calculation(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error)
}

type calculationServiceClient struct {
	cc *grpc.ClientConn
}

func NewCalculationServiceClient(cc *grpc.ClientConn) CalculationServiceClient {
	return &calculationServiceClient{cc}
}

func (c *calculationServiceClient) Calculation(ctx context.Context, in *CalculationRequest, opts ...grpc.CallOption) (*CalculationResponse, error) {
	out := new(CalculationResponse)
	err := c.cc.Invoke(ctx, "/calculator.CalculationService/Calculation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CalculationServiceServer is the server API for CalculationService service.
type CalculationServiceServer interface {
	// Unary call
	Calculation(context.Context, *CalculationRequest) (*CalculationResponse, error)
}

// UnimplementedCalculationServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCalculationServiceServer struct {
}

func (*UnimplementedCalculationServiceServer) Calculation(ctx context.Context, req *CalculationRequest) (*CalculationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Calculation not implemented")
}

func RegisterCalculationServiceServer(s *grpc.Server, srv CalculationServiceServer) {
	s.RegisterService(&_CalculationService_serviceDesc, srv)
}

func _CalculationService_Calculation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CalculationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CalculationServiceServer).Calculation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/calculator.CalculationService/Calculation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CalculationServiceServer).Calculation(ctx, req.(*CalculationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CalculationService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "calculator.CalculationService",
	HandlerType: (*CalculationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Calculation",
			Handler:    _CalculationService_Calculation_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "calculator/calculatorpb/calculator.proto",
}
